#
# Exodus2
#
# Looks for library to process exodusII files
# Needs netcdf library installed (this is checked by this module)
#

SET(MY_NETCDF_LIB_DIRS $ENV{MY_NETCDF_LIB_DIRS})
SET(MY_NETCDF_INC_DIRS $ENV{MY_NETCDF_INC_DIRS})
IF(NOT MY_NETCDF_LIB_DIRS OR NOT MY_NETCDF_INC_DIRS)
  SET(MY_NETCDF_LIB_DIRS $ENV{SAGE_LOCAL}/lib)
  SET(MY_NETCDF_INC_DIRS $ENV{SAGE_LOCAL}/include)  
ENDIF(NOT MY_NETCDF_LIB_DIRS OR NOT MY_NETCDF_INC_DIRS)

SET(MY_EXODUSII_LIB_DIRS $ENV{MY_EXODUSII_LIB_DIRS})
SET(MY_EXODUSII_INC_DIRS $ENV{MY_EXODUSII_INC_DIRS})
IF(NOT MY_EXODUSII_LIB_DIRS OR NOT MY_EXODUSII_INC_DIRS)
  SET(MY_EXODUSII_LIB_DIRS $ENV{SAGE_LOCAL}/lib)
  SET(MY_EXODUSII_INC_DIRS $ENV{SAGE_LOCAL}/include)  
ENDIF(NOT MY_EXODUSII_LIB_DIRS OR NOT MY_EXODUSII_INC_DIRS)

FIND_PATH(NETCDF_INCLUDE_PATH netcdf.h ${MY_NETCDF_INC_DIRS} NO_DEFAULT_PATH) 
FIND_PATH(EXODUSII_INCLUDE_PATH exodusII.h ${MY_EXODUSII_INC_DIRS} NO_DEFAULT_PATH)

FIND_LIBRARY(NETCDF_LIBRARY netcdf ${MY_NETCDF_LIB_DIRS} NO_DEFAULT_PATH)
FIND_LIBRARY(EXODUSII_LIBRARY exoIIv2c ${MY_EXODUSII_LIB_DIRS} NO_DEFAULT_PATH)
 
IF(EXODUSII_INCLUDE_PATH)
	SET(EXODUSII_INCLUDE_DIR ${EXODUSII_INCLUDE_DIR} ${EXODUSII_INCLUDE_PATH})
ENDIF(EXODUSII_INCLUDE_PATH)
 
IF(EXODUSII_LIBRARY)
	SET(EXODUSII_LIBRARIES ${EXODUSII_LIBRARIES} ${EXODUSII_LIBRARY})
ENDIF(EXODUSII_LIBRARY)
 
IF(NETCDF_INCLUDE_PATH)
	SET(EXODUSII_INCLUDE_DIR ${EXODUSII_INCLUDE_DIR} ${NETCDF_INCLUDE_PATH})
	SET(NETCDF_INCLUDE_DIR ${NETCDF_INCLUDE_PATH})
ENDIF(NETCDF_INCLUDE_PATH)

IF(NETCDF_LIBRARY)
	SET(EXODUSII_LIBRARIES ${EXODUSII_LIBRARIES} ${NETCDF_LIBRARY})
ENDIF(NETCDF_LIBRARY)
  
INCLUDE(FindPackageHandleStandardArgs)
find_package_handle_standard_args(EXODUSII DEFAULT_MSG EXODUSII_LIBRARY EXODUSII_INCLUDE_DIR NETCDF_LIBRARY NETCDF_INCLUDE_DIR)

