#
# HDF5
#

SET(MY_HDF5_LIB_DIRS $ENV{MY_HDF5_LIB_DIRS})
SET(MY_HDF5_INC_DIRS $ENV{MY_HDF5_INC_DIRS})

IF(NOT MY_HDF5_LIB_DIRS OR NOT MY_HDF5_INC_DIRS)
  SET(MY_HDF5_LIB_DIRS $ENV{SAGE_LOCAL}/lib)
  SET(MY_HDF5_INC_DIRS $ENV{SAGE_LOCAL}/include)  
ENDIF(NOT MY_HDF5_LIB_DIRS OR NOT MY_HDF5_INC_DIRS)

FIND_PATH(HDF5_INCLUDE_DIR hdf5.h ${MY_HDF5_INC_DIRS} NO_DEFAULT_PATH)
FIND_LIBRARY(HDF5_LIBRARY hdf5 ${MY_HDF5_LIB_DIRS} NO_DEFAULT_PATH) 

INCLUDE(FindPackageHandleStandardArgs)
FIND_PACKAGE_HANDLE_STANDARD_ARGS(HDF5 DEFAULT_MSG HDF5_INCLUDE_DIR HDF5_LIBRARY)
