#
# Modified AntTweakBar 1.1.3
#

SET(MY_ANTTWEAKBAR_LIB_DIRS $ENV{MY_ANTTWEAKBAR_LIB_DIRS})
SET(MY_ANTTWEAKBAR_INC_DIRS $ENV{MY_ANTTWEAKBAR_INC_DIRS})

IF(NOT MY_ANTTWEAKBAR_LIB_DIRS OR NOT MY_ANTTWEAKBAR_INC_DIRS)
  SET(MY_ANTTWEAKBAR_LIB_DIRS $ENV{SAGE_LOCAL}/lib)
  SET(MY_ANTTWEAKBAR_INC_DIRS $ENV{SAGE_LOCAL}/include)
ENDIF(MY_ANTTWEAKBAR_LIB_DIRS OR NOT MY_ANTTWEAKBAR_INC_DIRS)

FIND_PATH(ANTTWEAKBAR_INCLUDE_DIR AntTweakBar.h ${MY_ANTTWEAKBAR_INC_DIRS})
FIND_LIBRARY(ANTTWEAKBAR_LIBRARY AntTweakBar ${MY_ANTTWEAKBAR_LIB_DIRS})

INCLUDE(FindPackageHandleStandardArgs)
FIND_PACKAGE_HANDLE_STANDARD_ARGS(ANTTWEAKBAR DEFAULT_MSG ANTTWEAKBAR_LIBRARY ANTTWEAKBAR_INCLUDE_DIR)

#INCLUDE(CheckFunctionExists)
#message("${ANTTWEAKBAR_INCLUDE_DIR}/AntTweakBar.h")
#CHECK_SYMBOL_EXISTS("TwSetCurrentWndID" "${ANTTWEAKBAR_INCLUDE_DIR}/AntTweakBar.h" SYMBOL_FOUND)
#if(NOT SYMBOL_FOUND)
#	message(FATAL_ERROR "AntTweakBar found but not the modified version.")
#endif(NOT SYMBOL_FOUND)
#unset(SYMBOL_FOUND)
