#
# UMFPACK
#

SET(MY_UMFPACK_LIB_DIRS $ENV{MY_UMFPACK_LIB_DIRS})
SET(MY_UMFPACK_INC_DIRS $ENV{MY_UMFPACK_INC_DIRS})

IF(NOT MY_UMFPACK_LIB_DIRS OR NOT MY_UMFPACK_INC_DIRS)
  SET(MY_UMFPACK_LIB_DIRS $ENV{SAGE_LOCAL}/lib $ENV{SAGE_LOCAL}/lib/suitesparse)
  SET(MY_UMFPACK_INC_DIRS $ENV{SAGE_LOCAL}/include $ENV{SAGE_LOCAL}/include/suitesparse)
ENDIF(NOT MY_UMFPACK_LIB_DIRS OR NOT MY_UMFPACK_INC_DIRS)

FIND_PATH(UMFPACK_INCLUDE_DIR umfpack.h ${MY_UMFPACK_INC_DIRS} NO_DEFAULT_PATH)

FOREACH(L umfpack amd cholmod colamd camd metis ccolamd)
  SET(LIB ${L}-NOTFOUND)
  FIND_LIBRARY(LIB ${L} ${MY_UMFPACK_LIB_DIRS} NO_DEFAULT_PATH) 
  LIST(APPEND UMFPACK_LIBRARIES ${LIB})
ENDFOREACH(L)

INCLUDE(FindPackageHandleStandardArgs)
FIND_PACKAGE_HANDLE_STANDARD_ARGS(UMFPACK DEFAULT_MSG UMFPACK_LIBRARIES UMFPACK_INCLUDE_DIR)
