#
# GLEW
#

SET(MY_GLEW_LIB_DIRS $ENV{MY_GLEW_LIB_DIRS})
SET(MY_GLEW_INC_DIRS $ENV{MY_GLEW_INC_DIRS})

IF(NOT MY_GLEW_LIB_DIRS)
  SET(MY_GLEW_LIB_DIRS $ENV{SAGE_LOCAL}/lib)
  SET(MY_GLEW_INC_DIRS $ENV{SAGE_LOCAL}/include/GL)
ENDIF(NOT MY_GLEW_LIB_DIRS)

if(MSVC)
	set(GLEW_LIBRARY_NAME glew32)
else(MSVC)
	set(GLEW_LIBRARY_NAME GLEW)
endif(MSVC)

FIND_PATH(GLEW_INCLUDE_DIR glew.h ${MY_GLEW_INC_DIRS} NO_DEFAULT_PATH)
FIND_LIBRARY(GLEW_LIBRARY ${GLEW_LIBRARY_NAME} ${MY_GLEW_LIB_DIRS} NO_DEFAULT_PATH)

INCLUDE(FindPackageHandleStandardArgs)
FIND_PACKAGE_HANDLE_STANDARD_ARGS(GLEW DEFAULT_MSG GLEW_LIBRARY)
