#
# Judy
#

SET(MY_JUDY_LIB_DIRS $ENV{MY_JUDY_LIB_DIRS})
SET(MY_JUDY_INC_DIRS $ENV{MY_JUDY_INC_DIRS})

IF(NOT MY_JUDY_LIB_DIRS OR NOT MY_JUDY_INC_DIRS)
  SET(MY_JUDY_LIB_DIRS $ENV{SAGE_LOCAL}/lib)
  SET(MY_JUDY_INC_DIRS $ENV{SAGE_LOCAL}/include)  
ENDIF(NOT MY_JUDY_LIB_DIRS OR NOT MY_JUDY_INC_DIRS)

FIND_PATH(JUDY_INCLUDE_DIR Judy.h ${MY_JUDY_INC_DIRS}  NO_DEFAULT_PATH)
FIND_LIBRARY(JUDY_LIBRARY Judy ${MY_JUDY_LIB_DIRS} NO_DEFAULT_PATH)

INCLUDE(FindPackageHandleStandardArgs)
FIND_PACKAGE_HANDLE_STANDARD_ARGS(JUDY DEFAULT_MSG JUDY_LIBRARY JUDY_INCLUDE_DIR)
