#
# GLUT
#

SET(MY_GLUT_LIB_DIRS $ENV{MY_GLUT_LIB_DIRS})
SET(MY_GLUT_INC_DIRS $ENV{MY_GLUT_INC_DIRS})

IF(NOT MY_GLUT_LIB_DIRS)
  SET(MY_GLUT_LIB_DIRS $ENV{SAGE_LOCAL}/lib)
  SET(MY_GLUT_INC_DIRS $ENV{SAGE_LOCAL}/include/GL)
ENDIF(NOT MY_GLUT_LIB_DIRS)

if(MSVC)
	set(GLUT_LIBRARY_NAME freeglut)
else(MSVC)
	set(GLUT_LIBRARY_NAME glut)
endif(MSVC)

FIND_PATH(GLUT_INCLUDE_DIR freeglut.h ${MY_GLUT_INC_DIRS} NO_DEFAULT_PATH)
FIND_LIBRARY(GLUT_LIBRARY ${GLUT_LIBRARY_NAME} ${MY_GLUT_LIB_DIRS} NO_DEFAULT_PATH)

INCLUDE(FindPackageHandleStandardArgs)
FIND_PACKAGE_HANDLE_STANDARD_ARGS(GLUT DEFAULT_MSG GLUT_LIBRARY)
